--- # This is config for the dev environment
someTimeout:
  description: >
    This is some timeout value.  Isn't it great?
  value: 0

someNestedConfig:
  description: >
    This shows how your config can be an object.
  value:
    favoriteNumbers:
      - 7
      - 11
      - 13
      - 42
    address:
      street: Washington Street
      number: 1234
      city: Gilbert
      state: Arizona